services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
        - 80:80
        volumes:
        - ./src:/var/www/html/
        - ./php.ini:/usr/local/etc/php/conf.d/php.ini

    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 12345678
        volumes:
            - mysql-data:/var/lib/mysql
            - .:/docker-entrypoint-initdb.d

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    mysql-data:
