services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 12345678
        volumes:
            - mysql-data:/var/lib/mysql
            - ./db:/docker-entrypoint-initdb.d
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
    apache:
        build: .
        environment:
            - DB_HOST=db
            - DB_NAME=appDB
            - DB_USER=root
            - DB_PASSWORD=12345678
        volumes:
        - ./src:/var/www/html
        - ./config/apache.conf:/etc/apache2/sites-enabled/000-default.conf
        - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
    nginx:
        image: nginx
        ports: 
            - 80:80
        volumes:
        - ./static:/etc/nginx/html
        - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    redis:
        image: redis:alpine3.16
        restart: always
        ports:
            - 6379:6379
    redis-commander:
        image: rediscommander/redis-commander:latest
        restart: always
        environment:
        - REDIS_HOSTS=local:redis:6379
        ports:
            - 8081:8081
volumes:
    mysql-data: